[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
quadra = "YOUR_GENERATED_QUADRA_ADDRESS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "PATH_TO_YOUR_WALLET"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
